# -*- coding: utf-8 -*-
"""app.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kBxUEF_Kjv7wkcW_ER28Cjp6TAEZp3Nt
"""

import streamlit as st

from pages.home import show_home
from pages.dataset import show_dataset
from pages.preprocessing import show_preprocessing
from pages.augmentation import show_augmentation
from pages.classification import show_classification
from pages.comparison import show_comparison

st.set_page_config(
    page_title="Fruit Freshness Classification",
    page_icon="🍎",
    layout="wide"
)

st.sidebar.title("Fruit Classification")

menu = st.sidebar.radio(
    "Menu",
    [
        "Home",
        "Dataset",
        "Preprocessing",
        "Augmentation",
        "Classification",
        "Comparison"
    ]
)

if menu == "Home":
    show_home()

elif menu == "Dataset":
    show_dataset()

elif menu == "Preprocessing":
    show_preprocessing()

elif menu == "Augmentation":
    show_augmentation()

elif menu == "Classification":
    show_classification()

elif menu == "Comparison":
    show_comparison()