# -*- coding: utf-8 -*-
"""config.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1IJPdkj0_i2T-IOrAktpzdohpIQ--ReTu
"""

DATASET_PATH = "dataset_final"
PREPROCESS_PATH = "FruitDataset_Preprocess"
AUGMENT_PATH = "FruitDataset_Augmentation"

IMG_SIZE_PREPROCESS = 224
IMG_SIZE_CLASSIFICATION = 64