# -*- coding: utf-8 -*-
"""augment.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1t3cMz9TOulm1krGG9LQYHXe-ZiHpBjqf
"""

import cv2

def augment_image(image):

    augmented_images = []

    # Original
    augmented_images.append(image)

    # Rotation
    rows, cols = image.shape[:2]

    M = cv2.getRotationMatrix2D(
        (cols / 2, rows / 2),
        15,
        1
    )

    rotated = cv2.warpAffine(
        image,
        M,
        (cols, rows)
    )

    augmented_images.append(rotated)

    # Horizontal Flip
    flipped = cv2.flip(
        image,
        1
    )

    augmented_images.append(flipped)

    # Zoom
    zoom = cv2.resize(
        image,
        None,
        fx=1.2,
        fy=1.2
    )

    h, w = image.shape[:2]
    zh, zw = zoom.shape[:2]

    startx = zw // 2 - w // 2
    starty = zh // 2 - h // 2

    zoom = zoom[
        starty:starty + h,
        startx:startx + w
    ]

    augmented_images.append(zoom)

    return augmented_images