# -*- coding: utf-8 -*-
"""classifier.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tVfDC4ABitKsv7-igtYZ7XDXDezxBY2W
"""

import os
import cv2
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import streamlit as st

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder

from sklearn.neighbors import KNeighborsClassifier
from sklearn.svm import SVC
from sklearn.neural_network import MLPClassifier

from sklearn.metrics import (
    accuracy_score,
    ConfusionMatrixDisplay
)


# ==========================================
# Load Dataset
# ==========================================

def load_dataset(dataset_path, img_size):

    images = []
    labels = []

    classes = sorted(

        folder

        for folder in os.listdir(dataset_path)

        if os.path.isdir(
            os.path.join(dataset_path, folder)
        )

    )

    for class_name in classes:

        class_path = os.path.join(
            dataset_path,
            class_name
        )

        if not os.path.isdir(class_path):
            continue

        for image_name in os.listdir(class_path):

            image_path = os.path.join(
                class_path,
                image_name
            )

            img = cv2.imread(image_path)

            if img is None:
                raise ValueError(f"Gagal membaca gambar: {image_path}")

            img = cv2.cvtColor(
                img,
                cv2.COLOR_BGR2RGB
            )

            img = cv2.resize(
                img,
                (img_size, img_size)
            )

            images.append(img)
            labels.append(class_name)

    return np.array(images), np.array(labels)


# ==========================================
# Train Test Split
# ==========================================

def prepare_dataset(images, labels):

    if len(images) == 0:
        raise ValueError("Dataset kosong. Tidak ada gambar yang berhasil dimuat.")

    images = np.array(images)
    
    images = images.reshape(
        len(images),
        -1
    )

    encoder = LabelEncoder()

    labels = encoder.fit_transform(labels)

    X_train, X_test, y_train, y_test = train_test_split(

        images,

        labels,

        test_size=0.2,

        random_state=42,

        stratify=labels

    )

    return (

        images,

        labels,

        encoder,

        X_train,

        X_test,

        y_train,

        y_test

    )


# ==========================================
# KNN
# ==========================================

def train_knn(

    X_train,

    X_test,

    y_train,

    y_test

):

    best_accuracy = 0

    best_k = 0

    best_prediction = None

    best_model = None

    result = []

    for k in [1,3,5,7]:

        knn = KNeighborsClassifier(

            n_neighbors=k,

            metric="euclidean"

        )

        knn.fit(

            X_train,

            y_train

        )

        prediction = knn.predict(

            X_test

        )

        accuracy = accuracy_score(

            y_test,

            prediction

        )

        result.append({

            "K":k,

            "Accuracy":accuracy

        })

        if accuracy > best_accuracy:

            best_accuracy = accuracy

            best_k = k

            best_prediction = prediction

            best_model = knn

    return (

        best_model,

        best_k,

        best_accuracy,

        best_prediction,

        result

    )
    


# ==========================================
# SVM
# ==========================================

def train_svm(

    X_train,

    X_test,

    y_train,

    y_test

):

    kernels = [

        "linear",
         "poly"

    ]

    best_accuracy = 0

    best_kernel = ""

    best_prediction = None

    best_model = None

    result = []

    for kernel in kernels:

        svm = SVC(
            kernel=kernel,
            probability=True,
            random_state=42
        )

        svm.fit(

            X_train,

            y_train

        )

        prediction = svm.predict(

            X_test

        )

        accuracy = accuracy_score(

            y_test,

            prediction

        )

        result.append({

            "Kernel":kernel,

            "Accuracy":accuracy

        })

        if accuracy > best_accuracy:

            best_accuracy = accuracy

            best_kernel = kernel

            best_prediction = prediction

            best_model = svm

    return (

        best_model,

        best_kernel,

        best_accuracy,

        best_prediction,

        result

    )


# ==========================================
# ANN
# ==========================================

def train_ann(

    X_train,

    X_test,

    y_train,

    y_test

):

    ann = MLPClassifier(

        hidden_layer_sizes=(128,),

        activation="relu",

        solver="adam",

        max_iter=200,

        random_state=42

    )

    ann.fit(

        X_train,

        y_train

    )

    prediction = ann.predict(

        X_test

    )

    accuracy = accuracy_score(

        y_test,

        prediction

    )

    return (

        ann,

        accuracy,

        prediction

    )

@st.cache_data(show_spinner=False)
def load_cached_dataset(dataset_path, img_size):

    return load_dataset(
        dataset_path,
        img_size
    )

@st.cache_resource(show_spinner=False)
def get_model(
    model_name,
    dataset_path,
    img_size
):

    images, labels = load_cached_dataset(
        dataset_path,
        img_size
    )

    (
        images,
        labels,
        encoder,
        X_train,
        X_test,
        y_train,
        y_test
    ) = prepare_dataset(
        images,
        labels
    )

    if model_name == "KNN":

        model, _, _, _, _ = train_knn(
            X_train,
            X_test,
            y_train,
            y_test
        )

    elif model_name == "SVM":

        model, _, _, _, _ = train_svm(
            X_train,
            X_test,
            y_train,
            y_test
        )

    else:

        model, _, _ = train_ann(
            X_train,
            X_test,
            y_train,
            y_test
        )

    return model, encoder
# ==========================================
# Confusion Matrix
# ==========================================

def plot_confusion_matrix(

    y_test,

    prediction,

    classes,

    title

):

    fig, ax = plt.subplots(

        figsize=(8,6)

    )

    ConfusionMatrixDisplay.from_predictions(

        y_test,

        prediction,

        display_labels=classes,

        xticks_rotation=45,

        cmap="Blues",

        ax=ax

    )

    ax.set_title(title)

    return fig

# ==========================================
# Accuracy Comparison
# ==========================================

def compare_models(

    best_k,
    best_knn_accuracy,

    best_kernel,
    best_svm_accuracy,

    ann_accuracy

):

    return pd.DataFrame({

        "Model":[

            f"KNN (K={best_k})",

            f"SVM ({best_kernel})",

            "ANN"

        ],

        "Accuracy":[

            best_knn_accuracy,

            best_svm_accuracy,

            ann_accuracy

        ]

    })

def preprocess_input_image(image_path, img_size):

    img = cv2.imread(image_path)

    if img is None:
        raise ValueError(f"Gagal membaca gambar: {image_path}")

    img = cv2.cvtColor(
        img,
        cv2.COLOR_BGR2RGB
    )

    img = cv2.resize(
        img,
        (img_size,img_size)
    )


    img = img.reshape(
        1,
        -1
    )


    return img

def predict_image(
    model,
    encoder,
    image_path,
    img_size
):

    image = preprocess_input_image(
        image_path,
        img_size
    )

    prediction = model.predict(image)

    label = encoder.inverse_transform(prediction)[0]

    confidence = None

    if hasattr(model, "predict_proba"):

        confidence = np.max(
            model.predict_proba(image)
        )

    return label, confidence

def split_label(label):

    if label.startswith("Fresh"):

        fruit = label.replace("Fresh", "")

        condition = "Fresh"

    elif label.startswith("Rotten"):

        fruit = label.replace("Rotten", "")

        condition = "Rotten"

    else:

        fruit = label

        condition = "Unknown"

    return fruit, condition

