# -*- coding: utf-8 -*-
"""preprocess.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17yyhIE5pP4gAfT5n_3HhhCyPThxaHp2v
"""
import cv2
import numpy as np

from config import IMG_SIZE


def preprocess_image(image_path):

    img = cv2.imread(image_path)

    if img is None:
        return None

    img = cv2.resize(
        img,
        (IMG_SIZE, IMG_SIZE)
    )

    img = cv2.GaussianBlur(
        img,
        (5,5),
        0
    )

    hsv = cv2.cvtColor(
        img,
        cv2.COLOR_BGR2HSV
    )

    hsv[:,:,2] = cv2.equalizeHist(
        hsv[:,:,2]
    )

    img = cv2.cvtColor(
        hsv,
        cv2.COLOR_HSV2BGR
    )

    img = cv2.cvtColor(
        img,
        cv2.COLOR_BGR2HSV
    )

    img = img.astype(np.float32) / 255.0

    return img