# -*- coding: utf-8 -*-
"""augmentation.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fO9G9EP1cKFlNAqovzYCx-wXEHjAlufY
"""

import os
import cv2
import shutil
import matplotlib.pyplot as plt
import streamlit as st

from tqdm import tqdm

from config import PREPROCESS_PATH, AUGMENT_PATH
from utils.augment import augment_image


def show_augmentation():

    st.title("🔄 Augmentation")

    st.write(
        "Lakukan augmentasi pada hasil preprocessing untuk menambah variasi dataset."
    )

    if st.button(
        "🚀 Jalankan Augmentasi",
        use_container_width=True
    ):

        shutil.rmtree(
            AUGMENT_PATH,
            ignore_errors=True
        )

        os.makedirs(
            AUGMENT_PATH,
            exist_ok=True
        )

        progress_bar = st.progress(0)

        progress_text = st.empty()

        classes = sorted(os.listdir(PREPROCESS_PATH))

        total_class = len(classes)

        for index, class_name in enumerate(classes):

            class_path = os.path.join(
                PREPROCESS_PATH,
                class_name
            )

            if not os.path.isdir(class_path):
                continue

            save_class_path = os.path.join(
                AUGMENT_PATH,
                class_name
            )

            os.makedirs(
                save_class_path,
                exist_ok=True
            )

            progress_text.write(
                f"Augmenting **{class_name}**..."
            )

            for image_name in tqdm(os.listdir(class_path)):

                image_path = os.path.join(
                    class_path,
                    image_name
                )

                img = cv2.imread(image_path)

                if img is None:
                    continue

                imgs = augment_image(img)

                base = os.path.splitext(image_name)[0]

                names = [
                    "original",
                    "rotation",
                    "flip",
                    "zoom"
                ]

                for aug_img, name in zip(imgs, names):

                    save_path = os.path.join(
                        save_class_path,
                        f"{name}_{base}.jpg"
                    )

                    cv2.imwrite(
                        save_path,
                        aug_img
                    )

            progress_bar.progress(
                (index + 1) / total_class
            )

        progress_bar.empty()
        progress_text.empty()

        st.success("✅ Augmentation Finished")

    if not os.path.exists(AUGMENT_PATH):

        st.info(
            "Silakan jalankan augmentasi terlebih dahulu."
        )

        return

    classes = sorted(os.listdir(AUGMENT_PATH))

    if len(classes) == 0:

        st.warning(
            "Folder augmentasi masih kosong."
        )

        return

    st.subheader("📂 Jumlah Dataset Setelah Augmentasi")

    augment_info = []

    for folder in classes:

        folder_path = os.path.join(
            AUGMENT_PATH,
            folder
        )

        if os.path.isdir(folder_path):

            augment_info.append({
                "Class": folder,
                "Total Images": len(os.listdir(folder_path))
            })

    st.table(augment_info)

    st.subheader("🖼️ Contoh Hasil Augmentasi")

    fig = plt.figure(figsize=(15, 8))

    for i, class_name in enumerate(classes):

        img_name = os.listdir(
            os.path.join(
                AUGMENT_PATH,
                class_name
            )
        )[0]

        img_path = os.path.join(
            AUGMENT_PATH,
            class_name,
            img_name
        )

        img = cv2.imread(img_path)

        img = cv2.cvtColor(
            img,
            cv2.COLOR_BGR2RGB
        )

        plt.subplot(2, 3, i + 1)

        plt.imshow(img)

        plt.title(class_name)

        plt.axis("off")

    plt.tight_layout()

    st.pyplot(fig)