# -*- coding: utf-8 -*-
"""classification.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1OA8CoGN1wDPW7lPSN_1ocvIuCTvgR49n
"""

import streamlit as st
import matplotlib.pyplot as plt
import os

from config import AUGMENT_PATH
from config import IMG_SIZE_CLASSIFICATION

from utils.classifier import (

    load_dataset,

    prepare_dataset,

    train_knn,

    train_svm,

    train_ann,

    plot_confusion_matrix,

    compare_models,

    save_model

)

def show_classification():

    st.title("🤖 Image Classification")

    st.write(
        """
        Halaman ini digunakan untuk melakukan klasifikasi
        menggunakan algoritma KNN, SVM dan ANN.
        """
    )

    if not st.button(
        "🚀 Jalankan Klasifikasi",
        use_container_width=True
    ):
        return

    # ==========================================
    # Load Dataset
    # ==========================================

    if not os.path.exists(AUGMENT_PATH):

        st.warning(
            "Silakan lakukan proses Augmentation terlebih dahulu."
        )

        return

    images, labels = load_dataset(
        AUGMENT_PATH,
        IMG_SIZE_CLASSIFICATION
    )

    if len(images) == 0:

        st.error(
            "Dataset kosong."
        )

        return

    st.subheader("📊 Dataset Classification")

    st.write(f"Image Shape : {images.shape}")
    st.write(f"Label Shape : {labels.shape}")

    # ==========================================
    # Preview Dataset
    # ==========================================

    st.subheader("🖼️ Contoh Dataset")

    fig = plt.figure(figsize=(10,6))

    total_image = min(6, len(images))

    for i in range(total_image):

        plt.subplot(2,3,i+1)

        plt.imshow(images[i])

        plt.title(labels[i])

        plt.axis("off")

    plt.tight_layout()

    st.pyplot(fig)

    # ==========================================
    # Prepare Dataset
    # ==========================================

    (
        images,
        labels,
        encoder,
        X_train,
        X_test,
        y_train,
        y_test
    ) = prepare_dataset(
        images,
        labels
    )

    st.subheader("📊 Dataset Shape")

    st.write(
        f"Images Shape : {images.shape}"
    )

    st.subheader("🏷️ Label Encoding")

    label_table = {

        "Label": list(range(len(encoder.classes_))),
        "Class": list(encoder.classes_)

    }

    st.dataframe(
        label_table,
        use_container_width=True
    )

    # ==========================================
    # Train Test Split
    # ==========================================

    st.subheader("📊 Train Test Split")

    col1, col2 = st.columns(2)

    with col1:

        st.metric(
            "Training Data",
            X_train.shape[0]
        )

    with col2:

        st.metric(
            "Testing Data",
            X_test.shape[0]
        )
    # ==========================================
    # KNN Classification
    # ==========================================

    st.subheader("🤖 K-Nearest Neighbor (KNN)")

    with st.spinner("Training KNN..."):

        (
            best_knn_model,
            best_k,
            best_knn_accuracy,
            best_knn_pred,
            knn_results
        ) = train_knn(

            X_train,
            X_test,
            y_train,
            y_test

        )
        save_model(

            best_knn_model,

            encoder,

            "models/knn.pkl"

        )

    st.dataframe(
        knn_results,
        use_container_width=True
    )

    st.success(
        f"Best K : {best_k}"
    )

    st.success(
        f"Best Accuracy : {best_knn_accuracy:.4f}"
    )

    fig = plot_confusion_matrix(

        y_test,

        best_knn_pred,

        encoder.classes_,

        "Confusion Matrix - KNN"

    )

    st.pyplot(fig)
    st.divider()

    # ==========================================
    # SVM
    # ==========================================

    st.subheader(
        "🤖 Support Vector Machine (SVM)"
    )

    with st.spinner("Training SVM..."):

        (
            best_svm_model,
            best_kernel,
            best_svm_accuracy,
            best_svm_pred,
            svm_results
        ) = train_svm(

            X_train,
            X_test,
            y_train,
            y_test

        )
    save_model(

        best_svm_model,

        encoder,

        "models/svm.pkl"

    )

    st.dataframe(
        svm_results,
        use_container_width=True
    )

    st.success(
        f"Best Kernel : {best_kernel}"
    )

    st.success(
        f"Best Accuracy : {best_svm_accuracy:.4f}"
    )

    fig = plot_confusion_matrix(

        y_test,

        best_svm_pred,

        encoder.classes_,

        "Confusion Matrix - SVM"

    )

    st.pyplot(fig)
    st.divider()

    # ==========================================
    # ANN
    # ==========================================

    st.subheader(
        "🤖 Artificial Neural Network (ANN)"
    )

    with st.spinner("Training ANN..."):

        ann_model, ann_accuracy, ann_pred = train_ann(

            X_train,
            X_test,
            y_train,
            y_test

        )
    save_model(

        ann_model,

        encoder,

        "models/ann.pkl"

    )

    st.success(
        f"Accuracy : {ann_accuracy:.4f}"
    )

    fig = plot_confusion_matrix(

        y_test,

        ann_pred,

        encoder.classes_,

        "Confusion Matrix - ANN"

    )

    st.pyplot(fig)
    st.divider()

    # ==========================================
    # Accuracy Comparison
    # ==========================================

    st.subheader(
        "📊 Perbandingan Akurasi Model"
    )

    result = compare_models(

        best_k,
        best_knn_accuracy,

        best_kernel,
        best_svm_accuracy,

        ann_accuracy

    )

    result["Accuracy"] = result["Accuracy"].map(
        lambda x: f"{x:.2%}"
    )

    st.dataframe(

        result,

        use_container_width=True

    )