# -*- coding: utf-8 -*-
"""comparison.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1PMarAzW9C6xOcFibqym-f7LWagltpt7C
"""

import streamlit as st
import pandas as pd

from config import (
    DATASET_PATH,
    AUGMENT_PATH,
    IMG_SIZE_CLASSIFICATION
)

from utils.classifier import (
    load_dataset,
    prepare_dataset,
    train_svm
)


def show_comparison():

    st.title("📊 Dataset Comparison")

    st.write("""
    Membandingkan performa model SVM
    sebelum dan sesudah preprocessing &
    augmentation.
    """)

    if not st.button(
        "🚀 Jalankan Perbandingan",
        use_container_width=True
    ):
        return

    # ======================================
    # Dataset Original
    # ======================================

    st.subheader("📂 Dataset Original")

    images_ori, labels_ori = load_dataset(
        DATASET_PATH,
        IMG_SIZE_CLASSIFICATION
    )

    (
        images_ori,
        labels_ori,
        encoder_ori,
        X_train_ori,
        X_test_ori,
        y_train_ori,
        y_test_ori
    ) = prepare_dataset(
        images_ori,
        labels_ori
    )

    (
        best_kernel_ori,
        accuracy_ori,
        pred_ori,
        _
    ) = train_svm(

        X_train_ori,
        X_test_ori,
        y_train_ori,
        y_test_ori

    )

    st.success(
        f"Accuracy Dataset Original : {accuracy_ori:.4f}"
    )

    # ======================================
    # Dataset Augmentation
    # ======================================

    st.subheader("📂 Dataset Setelah Preprocessing")

    images_aug, labels_aug = load_dataset(
        AUGMENT_PATH,
        IMG_SIZE_CLASSIFICATION
    )

    (
        images_aug,
        labels_aug,
        encoder_aug,
        X_train_aug,
        X_test_aug,
        y_train_aug,
        y_test_aug
    ) = prepare_dataset(
        images_aug,
        labels_aug
    )

    (
        best_kernel_aug,
        accuracy_aug,
        pred_aug,
        _
    ) = train_svm(

        X_train_aug,
        X_test_aug,
        y_train_aug,
        y_test_aug

    )

    st.success(
        f"Accuracy Dataset Setelah Preprocessing : {accuracy_aug:.4f}"
    )

    # ======================================
    # Comparison
    # ======================================

    result = pd.DataFrame({

        "Dataset":[

            "Original",

            "Setelah Preprocessing"

        ],

        "Kernel":[

            best_kernel_ori,

            best_kernel_aug

        ],

        "Accuracy":[

            accuracy_ori,

            accuracy_aug

        ]

    })

    result["Accuracy"] = result["Accuracy"].map(
        lambda x: f"{x:.2%}"
    )

    st.subheader("📊 Perbandingan Akurasi")

    st.dataframe(
        result,
        use_container_width=True
    )