# -*- coding: utf-8 -*-
"""home.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1p2STJGv5xaAGHJsC2TspGYxmrCnHhmP8
"""

import streamlit as st

def show_home():

    st.title("🍎 Fruit Fresh vs Rotten Classification")

    st.markdown("""
    ## Digital Image Processing Project

    Sistem ini dapat melakukan:

    - Dataset Information
    - Image Preprocessing
    - Data Augmentation
    - Classification menggunakan KNN, SVM, dan ANN
    - Perbandingan Akurasi
    """)