# -*- coding: utf-8 -*-
"""preprocessing.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10ZP8VV9EjRy3xVpUq5YuLB7fr4wgX-5M
"""

import os
import cv2
import shutil
import numpy as np
import matplotlib.pyplot as plt
import streamlit as st

from tqdm import tqdm

from config import DATASET_PATH, PREPROCESS_PATH
from utils.preprocess import preprocess_image


def show_preprocessing():

    st.title("🔄 Preprocessing")

    st.write("Lakukan preprocessing pada seluruh dataset sebelum proses augmentasi dan klasifikasi.")
    dataset_path = os.path.join(DATASET_PATH, "train")
    # =====================================
    # Tombol Preprocessing
    # =====================================

    if st.button("🚀 Jalankan Preprocessing", use_container_width=True):

        shutil.rmtree(
            PREPROCESS_PATH,
            ignore_errors=True
        )

        os.makedirs(
            PREPROCESS_PATH,
            exist_ok=True
        )

        valid_extensions = (
            ".jpg",
            ".jpeg",
            ".png",
            ".jfif",
            ".webp"
        )

        progress_bar = st.progress(0)

        progress_text = st.empty()

        classes = sorted(os.listdir(dataset_path))

        total_class = len(classes)

        for index, class_name in enumerate(classes):

            class_path = os.path.join(
                dataset_path,
                class_name
            )

            if not os.path.isdir(class_path):
                continue

            progress_text.write(
                f"Processing **{class_name}**..."
            )

            save_class_path = os.path.join(
                PREPROCESS_PATH,
                class_name
            )

            os.makedirs(
                save_class_path,
                exist_ok=True
            )

            for image_name in tqdm(os.listdir(class_path)):

                if not image_name.lower().endswith(valid_extensions):
                    continue

                image_path = os.path.join(
                    class_path,
                    image_name
                )

                processed_img = preprocess_image(
                    image_path
                )

                if processed_img is None:
                    continue

                save_name = image_name.replace(".", "_")

                save_path = os.path.join(
                    save_class_path,
                    save_name + ".jpg"
                )

                save_img = (
                    processed_img * 255
                ).astype(np.uint8)

                cv2.imwrite(
                    save_path,
                    save_img
                )

            progress_bar.progress(
                (index + 1) / total_class
            )

        progress_bar.empty()
        progress_text.empty()

        st.success("✅ Preprocessing Finished")

    # =====================================
    # Tampilkan hasil preprocessing
    # =====================================

    if not os.path.exists(PREPROCESS_PATH):

        st.info(
            "Silakan jalankan preprocessing terlebih dahulu."
        )

        return

    classes = sorted(os.listdir(PREPROCESS_PATH))

    if len(classes) == 0:

        st.warning(
            "Folder preprocessing masih kosong."
        )

        return

    # =====================================
    # Jumlah Dataset
    # =====================================

    st.subheader("📂 Jumlah Dataset Setelah Preprocessing")

    preprocess_info = []

    for folder in classes:

        folder_path = os.path.join(
            PREPROCESS_PATH,
            folder
        )

        if os.path.isdir(folder_path):

            preprocess_info.append({
                "Class": folder,
                "Total Images": len(os.listdir(folder_path))
            })

    st.table(preprocess_info)

    # =====================================
    # Contoh Hasil
    # =====================================

    st.subheader("🖼️ Contoh Hasil Preprocessing")

    fig = plt.figure(figsize=(15,8))

    for i, class_name in enumerate(classes):

        images = os.listdir(
            os.path.join(
                PREPROCESS_PATH,
                class_name
            )
        )

        if len(images) == 0:
            continue

        img_name = images[0]

        img_path = os.path.join(
            PREPROCESS_PATH,
            class_name,
            img_name
        )

        img = cv2.imread(img_path)

        if img is None:
            continue

        img = cv2.cvtColor(
            img,
            cv2.COLOR_BGR2RGB
        )

        plt.subplot(2,3,i+1)

        plt.imshow(img)

        plt.title(class_name)

        plt.axis("off")

    plt.tight_layout()

    st.pyplot(fig)